version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_mlflow
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mlflow_results
      MYSQL_USER: mlflow_user
      MYSQL_PASSWORD: mlflow_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mlflow_network

  mlflow:
    build: .mlflow
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=mysql+pymysql://mlflow_user:mlflow_password@mysql:3306/mlflow_results
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    depends_on:
      - mysql
    networks:
      - mlflow_network
    command: mlflow server --backend-store-uri mysql+pymysql://mlflow_user:mlflow_password@mysql:3306/mlflow_results --default-artifact-root /mlflow/artifacts --host 0.0.0.0

  streamlit:
    build: .frontend
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=mysql
      - DB_USER=mlflow_user
      - DB_PASSWORD=mlflow_password
      - DB_NAME=mlflow_results
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mlflow
    networks:
      - mlflow_network
    command: streamlit run app.py --server.address 0.0.0.0

volumes:
  mysql_data:
  mlflow_artifacts:

networks:
  mlflow_network:
    driver: bridge
